CREATE TYPE "ProductCategory" AS ENUM (
  'FESTIVAL_GIFTS',
  'ANNIVERSARY_GIFTS',
  'PERSONALISED_GIFTS',
  'BIRTHDAY_GIFTS'
);

ALTER TABLE "Product"
ADD COLUMN "category" "ProductCategory" NOT NULL DEFAULT 'FESTIVAL_GIFTS';
